server:
  port: 7070
spring:
  application:
    name: user-command
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/instagram
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

axon:
  axonserver:
    servers: dev-geon-axonserver-ncl.nfra.io:8124